CREATE TABLE Usuarios(
	Id int IDENTITY(1,1) NOT NULL,
	Nombre varchar(20) NULL,
	Apellido varchar(20) NULL,	
 CONSTRAINT PK_Usuarios PRIMARY KEY CLUSTERED 
(
	Id ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


